config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 root 'mitames#index'
 
 resources :mitames

 resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :mitame
end

app/models/mitame.rb
class Mitame < ApplicationRecord
  has_one_attached :image
  has_many :memos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def create
     @comment = Memo.create(text: memo_params[:text], mitame_id: memo_params[:mitame_id])
    redirect_to "/mitames/#{@memo.mitame.id}"   #コメントと結びつくツイートの詳細画面に遷移する
  end
  
  private
  def memo_params
    params.permit(:text, :mitame_id)
  end
end

app/controllers/mitames_controller.rb
class MitamesController < ApplicationController
# before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

before_action :set_mitame, only: [ :show, :edit, :update, :destroy]
 def show
    @mitame = Mitame.find(params[:id])
 end
  def index
    @mitames = Mitame.order("created_at DESC").page(params[:page]).per(9)
  end
  def new
   @mitame = Mitame.new
  end
  
  def create
     @mitame = Mitame.new(mitame_params)
  end
  
  def destroy
   mitame = Mitame.find(params[:id])
   mitame.destroy
   redirect_to action: 'index'
  end
 
 
 def edit
   @mitame = Mitame.find(params[:id])
 end
 
 def update
  respond_to do |format|
   if @mitame.update(mitame_params)
    format.html {redirect_to @mitame, notice: 'Completed!!!!' }
    format.json {render :show, status: :ok, location: @mitame }
   else
    format.html {render :edit }
    format.json {render json: @book.errors, status: :unprocessable_entity }
   end
  end
 end
  
  private
  def mitame_params
    params.require(:mitame).permit(:name, :image, :text)
  end
  
 def set_mitame
  @mitame = Mitame.find(params[:id])
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
 def show
    @user = User.find(params[:id])
 end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/mitames_helper.rb
module MitamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>View0</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="./jquery.inview.js"></script>
    
    <!-- コード追加　Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加　Bootstrap JavaScript読み込みコード-->
    
    
  </head>

 <body>
  <div class="container">
    <header>
     <h1> &nbsp;&nbsp;&nbsp;&nbsp;One Coin Cooking!!!!!</h1>
      <nav>
       <ul>
       <li style="display:inline"><a href="/mitames/new">投稿する</a></li>
       &nbsp; <li style="display:inline"><a href="menu01.html">login</a></li> 
    
       </ul>
     </nav>
   </header>
    <%= yield %>
     <footer>
        <nav>
          <ul>
           <li style="display:inline"><a href="index.html">ホーム</a></li>
           <li style="display:inline"><a href="menu01.html">メニュー1</a></li> 
           <li style="display:inline"><a href="menu02.html">メニュー2</a></li>
          </ul>
      </nav>
    </footer>
    </div>
  </body>
</html>

app/views/mitames/create.html.erb
<div class="contents row">
  <div class="success">
    <center>
   <h3>
      あなたのワンコインメニューは公開されました!!
    </h3>
    <a class="btn" href="/mitames">トップページへ戻る</a>
    </center>
  </div>
</div>

app/views/mitames/edit.html.erb
<center><h1>Edit One Coin Menu....</h1></center>
 
   <div class="row form">
  <div class="col-lg-12">
    <%= form_for @mitame do |f| %>
      <center><h2>画像を変える</h2></center>
       <div class="form-group file">
        <%= f.file_field :image, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      
        <div class="col-lg-6">
          <%= f.text_field :first_name, placeholder: "名", class: "form-control" %>
        </div>
    
        <div class="col-lg-30">
          <%= f.text_field :recipi, placeholder: "レシピ", class: "form-control" %>
         </div>
    
      <div class="form-group">
        <center><%= f.submit "送信", class: "btn btn-primary withripple" %></center>
      </div>
    <% end %>
  </div>
</div>

 <center>
   &emsp;&emsp;<%= link_to '詳細', @mitame%> 
 &emsp;<%= link_to 'Main menu', mitames_path %> 
 </center>

app/views/mitames/index.html.erb
<!--<div class="container">-->
<% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
  <!-- ユーザーがログインしていた時の処理 -->
   <h6>&ensp; 現在 <%= current_user.id %> さんがログインしています </h6> <!-- ここを追加します -->
  <h6> &ensp;メールアドレス： <%= current_user.email %> </h6>
 &ensp; <%=link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
<% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
  <h6> &ensp;現在ログインしていませんけど。。。。。 </h6>
  &ensp;<%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
  &ensp;<%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
<% end %>
<div class="container">

<div class="flex">

   <% @mitames.each do |mitame| %>
    <ul class="list">
     <li class="list-mv02"" style="background-image: url(<%= mitame.image %>);">
      <%= simple_format(mitame.text) %>
      <span class="name"><%= mitame.name %></span>
      <p><%= link_to '詳細', "/mitames/#{mitame.id}", method: :get %></li>
     </li>
	</ul>
   <% end %>
    <%= paginate(@mitames) %>
	 

</div>
</div>

app/views/mitames/new.html.erb
<div class="container">
  
  <div class="contents row">
   <%= form_for @mitame do |f| %>
    <center><h3>
      投稿する
    </h3></center>
    
      <div class="form-group file">
        <%= f.file_field :image, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      
       <p>
        <div class="col-lg-10">
           <%= f.label :name, "名前" %>
           <%= f.text_field :name, placeholder: 'nickname' %>
        </div>
        </div></center></p>
        
        <div align="left">
        <div class="col-lg-15">
          <p><%= f.label :text, "レシピ" %></p>
          <%= f.text_field :text, placeholder: "レシピ", class: "form-control" %>
         </div>
         
          <div class="col-lg-15">
          <p><%= f.label :text, "材料１" %></p>
          <%= f.text_field :text, placeholder: "レシピ", class: "form-control" %>
         </div>
         
          <div class="col-lg-15">
          <p><%= f.label :text, "材料２" %></p>
          <%= f.text_field :text, placeholder: "レシピ", class: "form-control" %>
         </div>
         
          <div class="col-lg-15">
          <p><%= f.label :text, "材料３" %></p>
          <%= f.text_field :text, placeholder: "レシピ", class: "form-control" %>
         </div>
         
          <div class="col-lg-15">
          <p><%= f.label :text, "材料４" %></p>
          <%= f.text_field :text, placeholder: "レシピ", class: "form-control" %>
         </div>
         
          <div class="col-lg-15">
          <p><%= f.label :text, "材料５" %></p>
          <%= f.text_field :text, placeholder: "レシピ", class: "form-control" %>
         </div>
    
      <div class="form-group">
        <center><%= f.submit "送信", class: "btn btn-primary withripple" %></center>
      </div>
      <% end %>
    </div>
</div>

app/views/mitames/show.html.erb
<center><div class="container">

<div class="inline-block_test">
 <div class=box1>
     <div class="image" style="background-image: url(<%= @mitame.image %>) "></div>
  </div>
   <p><div class="box2" >
      <材料>
       <p></p>
        <form method="get" action="output.html" oninput="result.value = Number(a.value) + Number(b.value)+ Number(c.value)+ Number(d.value)+ Number(e.value);">
        <p>ごはん<input type="number" name="a" value="0"style="width:80px;" >
        <p>+ </p>たまご<input type="number" name="b" value="0" style="width:80px;" >
        <p>+ </p>たまご<input type="number" name="c" value="0" style="width:80px;" >
        <p>+ </p>たまご<input type="number" name="d" value="0" style="width:80px;" >
        <p>+ </p>たまご<input type="number" name="e" value="0" style="width:80px;" ></p>
    </div></p> 
    
    <div class="box3" >
        かかった時間
      </div>
      <div class="box4" >
       金額
  
       <p>計算結果：<output name="result">0</output></p>
       
       <script>
       var score = "result.value"
if (score >= 501) {
document.write(“ワンコインじゃ作れないんですけど、、、、”);
} else {
document.write(“good”);
}
</script>

      <!--<p><input type="submit" value="送信する"> <input type="reset" value="リセット"></p>-->

       </form>
      </div>  
</div>
<div class="inline-block_test2">
    
    <div class="box5" > <作り方＞ 
     <div align="left">
      <%= simple_format(@mitame.text) %>
     </div>
     </div>
    <p></p>    
  
    <div class="box6" > <コメント＞ 
    </div> 
      <p>
    <%= link_to '編集', edit_mitame_path(@mitame) %>
    <%= link_to '削除',"/mitames/#{@mitame.id}", method: :delete %>
    </p>
    
    <div class="container"> 
    <!-- ここからフォーム -->
      <%= form_tag("/mitames/#{@mitame.id}/comments", method: :post) do %>
        <textarea name="text" placeholder="コメントする" rows="2" cols="30"></textarea>
        <input type="submit" value="SENT">
      <% end %>
  </div>
</div>
 